# Generated by Django 2.2.5 on 2019-09-17 13:29

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CubesensorsData',
            fields=[
                ('sensorId', models.TextField(db_column='SensorId')),
                ('measurementTime', models.DateTimeField(
                    db_column='MeasurementTime', primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(
                    blank=True, db_column='Temperature', null=True)),
                ('pressure', models.IntegerField(
                    blank=True, db_column='Pressure', null=True)),
                ('humidity', models.IntegerField(
                    blank=True, db_column='Humidity', null=True)),
                ('voc', models.IntegerField(blank=True, db_column='Voc', null=True)),
                ('light', models.IntegerField(
                    blank=True, db_column='Light', null=True)),
                ('noise', models.IntegerField(
                    blank=True, db_column='Noise', null=True)),
                ('battery', models.IntegerField(
                    blank=True, db_column='Battery', null=True)),
                ('cable', models.IntegerField(
                    blank=True, db_column='Cable', null=True)),
                ('vocResistance', models.IntegerField(
                    blank=True, db_column='VocResistance', null=True)),
                ('rssi', models.IntegerField(blank=True, db_column='Rssi', null=True)),
            ],
            options={
                'db_table': 'cubesensors_data',
                'managed': settings.TESTING,
            },
        ),
    ]
