# Generated by Django 2.2.5 on 2019-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideTemperature',
            fields=[
                ('measurementTime', models.DateTimeField(
                    blank=True, db_column='MeasurementTime', primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(
                    blank=True, db_column='Temperature', null=True)),
            ],
            options={
                'db_table': 'outside_temperature',
            },
        ),
    ]
